version: "0.5"

environment:
  - "GLOBAL_ENV_VAR=1"
log_location: salz.log
log_level: debug

processes:
  postgres:
    command: "nix run .#db"
    availability:
      restart: "always"
    ready_log_line: "database system is ready to accept connections"

  minio:
    command: "nix run .#minio"
    availability:
      restart: "always"
    ready_log_line: "MinIO Object Storage Server"

  minio-ready:
    command: |
      # check for the salz bucket, create if not exists
      if ! mc ls local/salz | grep "salz"
      then
        echo "Salz bucket doesn't exist, creating"
        mc mb local/salz
      fi
    depends_on:
      minio:
        condition: process_log_ready

  api:
    command: "nix run .#api"
    availability:
      restart: "always"
    ready_log_line: "Listening and serving HTTP"
    depends_on:
      postgres:
        condition: process_log_ready
      minio-ready:
        condition: process_completed
